name: Build & Test

on:
  push:
    branches: [ "main", "rel-*" ]

env:
  NAME: Nanak

jobs:

  test:

    runs-on: ubuntu-22.04

    timeout-minutes: 10

    env:
      NAME: Planet

    needs: build

    steps:

      - name: Step inside test job
        run: echo "Hello $NAME"

      - name: Another step
        run: echo "This is another step in the same job"

  build:

    runs-on: ubuntu-20.04

    timeout-minutes: 5

    steps:

      - name: Greet user
        run: echo "Hello $NAME"

      - name: Another step
        run: echo "This is another step in the same job"


